### PR TITLE
Detect TestCaseSource attributes defined in base class.

### LINKED ISSUE #320: Incorrect NUnit1011 when TestCaseSource references a base class member
Repros in 0.4.0–0.6.0, not present in 0.3.0

```cs
using System.Collections.Generic;
using NUnit.Framework;

class Base
{
    public static IEnumerable<string> TargetFrameworks { get; } = new[] { "net48", "netcoreapp3.1" };
}

class Derived : Base
{
    // ❌ NUnit1011 The TestCaseSource argument 'TargetFrameworks' does not specify an existing member
    //              ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
    [TestCaseSource(nameof(TargetFrameworks))]
    public void Test(string targetFramework)
    {
    }
}
```

### PR DESCRIPTION
**Pull request by manfred-brands**
Fixes #320

### CODE REVIEW

File: src/nunit.analyzers/SourceCommon/SourceHelpers.cs [hunk 1]
```diff
@@ -79,12 +79,27 @@ internal static class SourceHelpers
...
+
+        public static ISymbol? GetMember(this INamedTypeSymbol typeSymbol, string name)
+        {
+            ISymbol? symbol = typeSymbol
+                .GetMembers(name)
                 .FirstOrDefault(m => m.Kind == SymbolKind.Field
                     || m.Kind == SymbolKind.Property
                     || m.Kind == SymbolKind.Method);
 
+            if (symbol is null && typeSymbol.BaseType != null)
```
Comment (jnm2) [inline src/nunit.analyzers/SourceCommon/SourceHelpers.cs:93]: I think there needs to be a loop. A test that places the test case source in the base class of the base class would indicate this.

Comment (jnm2) [reply src/nunit.analyzers/SourceCommon/SourceHelpers.cs:93]: Never mind, I missed the recursion.

**Review by mikkelbu — APPROVED** [review]
Looks good. Thanks for this improvement @manfred-brands.
