### PR TITLE
Fix DateOnly / TimeOnly parameters is TestCaseUsage

### LINKED ISSUE #820: NUnit1001 compains about DateOnly parameters
```csharp
    [TestCase("2024-09-25")]
    [TestCase("2024-09-26")]
    [TestCase("2024-09-27")]
    public async Task TestDateOnly(DateOnly expectedDate)
    {
...
    }
```

NUnit1001 is triggered here, even though it works perfeclty fine if I disable this analyzer.

### PR DESCRIPTION
**Pull request by Dreamescaper**
Fixes #820 .

I had to update test project to use net8.0 here (to be able to actually test DateOnly / TimeOnly parameters), hope it's ok.

### CODE REVIEW

File: src/nunit.analyzers/Extensions/AttributeArgumentTypedConstantExtensions.cs [hunk 1]
```diff
@@ -26,32 +26,37 @@ internal static class AttributeArgumentTypedConstantExtensions
...
         // Intrinsic type converters for types
         // https://github.com/dotnet/runtime/blob/master/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectTypeDescriptionProvider.cs
-        // For converters that exist in .NET Standard 1.6 we use the converter.
+        // For converters that exist in .NET Standard 2.0 we use the converter.
         // Otherwise, we assume that the converter exists and it can convert the value.
-        private static readonly List<(Type type, Lazy<TypeConverter>? typeConverter)> IntrinsicTypeConverters =
+        private static readonly List<(string fullName, Lazy<TypeConverter>? typeConverter)> IntrinsicTypeConverters =
             new()
             {
-                (typeof(bool), new Lazy<TypeConverter>(() => new BooleanConverter())),
```
Comment (Dreamescaper) [inline src/nunit.analyzers/Extensions/AttributeArgumentTypedConstantExtensions.cs:34]: Updated mapping per TypeConverter updates:
https://github.com/dotnet/runtime/blob/main/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectTypeDescriptionProvider.cs#L154

Had to update it to string from Type, as netstandard2.0 does not have  DateTime/DateOnly/etc types.

File: src/nunit.analyzers/nunit.analyzers.csproj [hunk 2]
```diff
@@ -12,7 +12,6 @@
     <PackageReference Include="Nullable" Version="1.3.1" PrivateAssets="all" />
     <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4" />
     <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="3.11.0" />
-    <PackageReference Include="System.ComponentModel.TypeConverter" Version="4.3.0" />
```
Comment (Dreamescaper) [inline src/nunit.analyzers/nunit.analyzers.csproj:15]: This package is not needed on netstandard2.0

**Comment by Dreamescaper** [comment]
Appveyor build failed, but I'm not really fure why:
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: .NETCoreApp,Version=v8.0

**Comment by mikkelbu** [comment]
> Appveyor build failed, but I'm not really fure why: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: .NETCoreApp,Version=v8.0

My time is very limited today due to new year's eve, but perhaps this is related to the cake tool? At least the bump to version 5.0 fails with
https://ci.appveyor.com/project/mikkelbu/nunit-analyzers/builds/51103770
```
.\build.ps1 --target="Appveyor" --configuration="Release" --targetFramework="netstandard2.0"
C:\Users\appveyor\AppData\Local\Temp\1\243f61e3-174d-4243-bbfd-5f4dd437f312\restore.csproj : error NU1202: Package Cake.Tool 5.0.0 is not compatible with net6.0 (.NETCoreApp,Version=v6.0) / any. Package Cake.Tool 5.0.0 supports:
C:\Users\appveyor\AppData\Local\Temp\1\[24](https://ci.appveyor.com/project/mikkelbu/nunit-analyzers/builds/51103770#L24)3f61e3-174d-4243-bbfd-5f4dd437f312\restore.csproj : error NU1202:   - net8.0 (.NETCoreApp,Version=v8.0) / any
C:\Users\appveyor\AppData\Local\Temp\1\243f61e3-174d-4243-bbfd-5f4dd437f312\restore.csproj : error NU1202:   - net9.0 (.NETCoreApp,Version=v9.0) / any
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Package "cake.tool" failed to restore, due to Microsoft.DotNet.ToolPackage.ToolPackageException: The tool package could not be restored.
```

So perhaps bumping the cake tool will solve the problem (I've not checked if there are any breaking changes between 3.2.0 and 5.0.0. Perhaps bumping to version 4 will be enough?

**Comment by mikkelbu** [comment]
@Dreamescaper Sorry about the WIP and moving the PR to draft and back again. I was hoping that this was enough to retrigger the builds. I've updated cake to version 4 on master and I hope this is enough to solve the problem with AppVeyor

**Comment by Dreamescaper** [comment]
@mikkelbu 
It seems to work just fine after merge from master, thanks for the help!

**Review by mikkelbu — APPROVED** [review]
The changes look sound @Dreamescaper. I'm a bit unsure why we need the bump to .NET8 as DateOnly and TimeOnly were already part of .NET 6, but I think I might be missing something obvious :).

Not that I've against the bump - I just thought from #677 that it would require update of the Roslyn Analyzer as well as larger consequential changes.

I've approved it, but I would prefer if @manfred-brands can take a second look before we merge this as I think he has a better understanding of the bump than I have (also I would like to test the generated nuget package locally).

File: src/nunit.analyzers.tests/TestCaseUsage/TestCaseUsageAnalyzerTests.cs [hunk 3]
```diff
@@ -824,6 +835,18 @@ public void TestWithGenericParameter<T>(T arg1) { }
     }");
             RoslynAssert.Valid(this.analyzer, testCode);
         }
+
+        [TestCaseSource(nameof(SpecialConversions_NET6))]
```
Comment (manfred-brands) [inline src/nunit.analyzers.tests/TestCaseUsage/TestCaseUsageAnalyzerTests.cs]: This code is inside an #if NUNIT4 conditional, but works fine with NUNIT3.
I have moved the method.

**Review by manfred-brands — APPROVED** [review]
Looks good now.
