### PR TITLE
fix: Handle intrinsic type converters by hardcoded converters

### LINKED ISSUE #196: Avoid loading new assemblies into the VS process
Issue raised based on comments from @jnm2 and @JohanLarsson in https://gitter.im/GuOrg/Gu.Roslyn.Asserts?at=5e793252b08f3e0abf8c2224.

So instead of loading types and possibly new assemblies into the VS process we handle intrinsic type converters directly and will handle custom type converters in a subsequent issue - #197. If a converter (from string) exists then we assume that it is able to convert to the target type. We loose the ability to mark actual string values that does not satisfy the correct format as failures, but that is the price to pay using static analysis.

Extract from Gitter.
> This is not a good idea:
https://github.com/nunit/nunit.analyzers/blob/master/src/nunit.analyzers/Extensions/AttributeArgumentSyntaxExtensions.cs#L154
this could load new assemblies into the VS process
Anything in the GAC or VS directories
...

### PR DESCRIPTION
**Pull request by mikkelbu**
Fixes #196

Note that `VersionConverter` and `CultureInfoConverter` does not exist in netstandard1.6.

### CODE REVIEW

File: src/nunit.analyzers/Extensions/AttributeArgumentSyntaxExtensions.cs [hunk 1]
```diff
@@ -138,45 +145,39 @@ private static bool TryChangeType(ITypeSymbol targetType, object argumentValue)
...
             }
 
-            return $"{string.Join(".", namespaces)}.{typeName}";
-        }
+            var typeConverter = targetType.typeConverter.Value;
+            if (typeConverter.CanConvertFrom(argumentValue.GetType()))
+            {
+                try
+                {
+                    typeConverter.ConvertFrom(null, CultureInfo.InvariantCulture, argumentValue);
```
Comment (jnm2) [inline src/nunit.analyzers/Extensions/AttributeArgumentSyntaxExtensions.cs:171]: Keep in mind that both `CanConvertFrom` and `ConvertFrom` may behave differently depending on which version of .NET Framework or .NET Core the analyzer is executing on. The framework and version that the analyzer is executing on will usually not match the version and framework that the tests execute on.

Comment (mikkelbu) [reply src/nunit.analyzers/Extensions/AttributeArgumentSyntaxExtensions.cs:171]: Thanks for the warning. I'll keep that in mind. My plan is to go with this initially, but if we run into differences then we can choose the safer approach and just assume that strings can always be converted into the mentioned types.

**Comment by Dreamescaper** [comment]
LGTM
