### PR TITLE
Fix enum handling in TestCaseUsageAnalyzer

### LINKED ISSUE #162: NUnit1001: False positive
Downloaded 0.1.0-dev-00205, analyzed my solution and I get a false positive for NUnit1001 when the types have an implicit conversion available.

I'm using NUnit 2.6.7, but I don't expect this to be a problem in NUnit3 either.

The error reports (for both these cases):
"The value of the argument at position '0' cannot be assigned to the argument 'value'"

```csharp
[TestCase(uint.MaxValue, "4294967295")]
[TestCase(0x8FFFFFFF, "2415919103")]
public void ClsCompliantCtor(long value, string output) {
 ...
}
```

### LINKED ISSUE #165: AD0001 Crash: TestCase contains int instead of enum
Version: NUnit.Analyzer-0.1.0-dev-00205
Visual Studio 2019
NUnit 2.6.7

When analyzing a project, the following crash occurred by the analyzer:
```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0001	Analyzer 'NUnit.Analyzers.TestCaseUsage.TestCaseUsageAnalyzer' threw an exception of type 'System.ArgumentNullException' with message 'Value cannot be null.
Parameter name: type'.	HBAS.Automation.Trace.Dlt.V850Test		1	Active	Analyzer 'NUnit.Analyzers.TestCaseUsage.TestCaseUsageAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: HBAS.Automation.Trace.Dlt.V850Test
SyntaxTree: C:\Users\jcurl\Documents\Programming\HELIOS\helios.devfxio\framework\tracereader\TraceReader.Dlt\HBAS.Automation.Trace.Dlt.V850Test\Dlt\TraceLineV850ToDltTest.cs
SyntaxNode: TestCase(0xFF, DltType.LOG_ERROR ... [AttributeSyntax]@[7194..7227) (139,9)-(139,42)

System.ArgumentNullException: Value cannot be null.
Parameter name: type
   at System.ComponentModel.TypeDescriptor.GetDescriptor(Type type, String typeName)
   at System.ComponentModel.TypeDescriptor.GetConverter(Type type)
   at NUnit.Analyzers.Extensions.AttributeArgumentSyntaxExtensions.CanAssignTo(AttributeArgumentSyntax this, ITypeSymbol target, SemanticModel model)
   at NUnit.Analyzers.TestCaseUsage.TestCaseUsageAnalyzer.AnalyzePositionalArgumentsAndParameters(SyntaxNodeAnalysisContext context, ImmutableArray`1 attributePositionalArguments, ImmutableArray`1 methodParameters)
   at NUnit.Analyzers.TestCaseUsage.TestCaseUsageAnalyzer.AnalyzeAttribute(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__53`1.<ExecuteSyntaxNodeAction>b__53_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.
```

The file that caused this issue is attached.

It seems to be related to:
```csharp
[TestCase(SystemMessageTypes.Normal, DltType.LOG_INFO)]
[TestCase(SystemMessageTypes.VersionEvent, DltType.LOG_INFO)]
[TestCase(SystemMessageTypes.Reset, DltType.LOG_INFO)]
[TestCase(SystemMessageTypes.TimeStamp, DltType.LOG_INFO)]
[TestCase(SystemMessageTypes.BufferDump, DltType.LOG_INFO)]
[TestCase(SystemMessageTypes.BufferDumpEnd, DltType.LOG_INFO)]
[TestCase(SystemMessageTypes.BufferThreshold, DltType.LOG_WARN)]
[TestCase(SystemMessageTypes.BufferFull, DltType.LOG_WARN)]
[TestCase(SystemMessageTypes.BytesSkipped, DltType.LOG_ERROR)]
[TestCase(SystemMessageTypes.UnknownId, DltType.LOG_ERROR)]
[TestCase(SystemMessageTypes.MessageCorruption, DltType.LOG_ERROR)]
[TestCase(SystemMessageTypes.MemoryMessageCorruption, DltType.LOG_ERROR)]
[TestCase(SystemMessageTypes.MessageConversionError, DltType.LOG_ERROR)]
[TestCase(0xFF, DltType.LOG_ERROR)]
public void CheckDltType(SystemMessageTypes v850Type, DltType dltType)
{
    DltLineConfig config = new DltLineConfig();

    IV850ModuleNameTranslator moduleTranslator = new V850ShortModuleName();
    TraceLineV850ToDlt traceLineConverter = new TraceLineV850ToDlt(moduleTranslator, config);
    TraceLineDlt dltLine = traceLineConverter.CreateDltLine("LogText", "Custom text", TimeSpan.FromSeconds(11),
        "MOD_SYSTEM", DateTimeHelper.UnixStartDate, v850Type);

    Assert.That(dltType, Is.EqualTo(dltLine.Type));
}
```

in particular the line:
```
[TestCase(0xFF, DltType.LOG_ERROR)]
```

Note, this is a valid test case, as .NET treats enums as an `int` underlying.

[TraceLineV850ToDltTest.zip](https://github.com/nunit/nunit.analyzers/files/3795504/TraceLineV850ToDltTest.zip)

### PR DESCRIPTION
**Pull request by Dreamescaper**
Fixes #165
Fixes #162

### CODE REVIEW

File: src/nunit.analyzers/Extensions/AttributeArgumentSyntaxExtensions.cs [hunk 1]
```diff
@@ -4,13 +4,16 @@
...
+using Microsoft.CodeAnalysis.CSharp;
 using Microsoft.CodeAnalysis.CSharp.Syntax;
 
 namespace NUnit.Analyzers.Extensions
 {
     internal static class AttributeArgumentSyntaxExtensions
     {
-        internal static bool CanAssignTo(this AttributeArgumentSyntax @this, ITypeSymbol target, SemanticModel model)
+        internal static bool CanAssignTo(this AttributeArgumentSyntax @this, ITypeSymbol target, SemanticModel model,
+            bool allowImplicitConversion = false,
```
Comment (Dreamescaper) [inline src/nunit.analyzers/Extensions/AttributeArgumentSyntaxExtensions.cs]: parametrized, because such conversions are allowed for test arguments, but not for ExpectedResult value.
